typedef enum {
    ATTRIBUTE_SELECTOR_NONE,
    ATTRIBUTE_SELECTOR_ACTIVE,
    ATTRIBUTE_SELECTOR_CHECKED,
    ATTRIBUTE_SELECTOR_DISABLED,
    ATTRIBUTE_SELECTOR_EMPTY,
    ATTRIBUTE_SELECTOR_ENABLED,
    ATTRIBUTE_SELECTOR_FOCUS,
    ATTRIBUTE_SELECTOR_HOVER
} GViewAttributeSelector;

typedef struct {
    GViewAttributeSelector selector;
} GViewAttribute;