#ifndef GVIEWPROPERTY_H
#define GVIEWPROPERTY_H

typedef enum {
    PROPERTY_TYPE_NONE,
    PROPERTY_TYPE_GCOLOR,
    PROPERTY_TYPE_GRECT,
    PROPERTY_TYPE_GTHICKNESS,
    PROPERTY_TYPE_ALIGNMENT,
    PROPERTY_TYPE_ENUM, 
    PROPERTY_TYPE_POINTER,
    PROPERTY_TYPE_STRING
} GViewPropertyType;

typedef enum {
    
} GViewSystemProperty;


#endif // GVIEWPROPERTY