#ifndef GSVGELEMENTS_H
#define GSVGELEMENTS_H

// GSPCore - GSvgElements.h
// This file defines structures to represent the available elements
// in the SVGTiny 1.2 specification.


typedef enum {
    SVG_ELEMENT_TYPE_A,
    SVG_ELEMENT_TYPE_ANIMATE,
    SVG_ELEMENT_TYPE_ANIMATE_COLOR,
    SVG_ELEMENT_TYPE_ANIMATE_MOTION,
    SVG_ELEMENT_TYPE_ANIMATE_TRANSFORM,
    SVG_ELEMENT_TYPE_ANIMATION,
    SVG_ELEMENT_TYPE_AUDIO,
    SVG_ELEMENT_TYPE_CIRCLE,
    SVG_ELEMENT_TYPE_DEFS,
    SVG_ELEMENT_TYPE_DESC,
    SVG_ELEMENT_TYPE_DISCARD,
    SVG_ELEMENT_TYPE_ELLIPSE,
    SVG_ELEMENT_TYPE_FONT,
    SVG_ELEMENT_TYPE_FONT_FACE,
    SVG_ELEMENT_TYPE_FONT_FACE_SRC,
    SVG_ELEMENT_TYPE_FONT_FACE_URI,
    SVG_ELEMENT_TYPE_FOREIGN_OBJECT,
    SVG_ELEMENT_TYPE_G,
    SVG_ELEMENT_TYPE_GLPYH,
    SVG_ELEMENT_TYPE_HANDLER,
    SVG_ELEMENT_TYPE_HKERN,
    SVG_ELEMENT_TYPE_IMAGE,
    SVG_ELEMENT_TYPE_LINE,
    SVG_ELEMENT_TYPE_LINEAR_GRADIENT,
    SVG_ELEMENT_TYPE_LISTENER,
    SVG_ELEMENT_TYPE_METADATA,
    SVG_ELEMENT_TYPE_MISSING_GLYPH,
    SVG_ELEMENT_TYPE_MPATH,
    SVG_ELEMENT_TYPE_PATH,
    SVG_ELEMENT_TYPE_POLYGON,
    SVG_ELEMENT_TYPE_POLYLINE,
    SVG_ELEMENT_TYPE_PREFETCH,
    SVG_ELEMENT_TYPE_RADIAL_GRADIENT,
    SVG_ELEMENT_TYPE_RECT,
    SVG_ELEMENT_TYPE_SCRIPT,
    SVG_ELEMENT_TYPE_SET,
    SVG_ELEMENT_TYPE_SOLID_COLOR,
    SVG_ELEMENT_TYPE_STOP,
    SVG_ELEMENT_TYPE_SVG,
    SVG_ELEMENT_TYPE_SWITCH,
    SVG_ELEMENT_TYPE_TBREAK,
    SVG_ELEMENT_TYPE_TEXT,
    SVG_ELEMENT_TYPE_TEXT_AREA,
    SVG_ELEMENT_TYPE_TITLE,
    SVG_ELEMENT_TYPE_TSPAN,
    SVG_ELEMENT_TYPE_USE,
    SVG_ELEMENT_TYPE_VIDEO
} GSvgElementType;

typedef struct {
    const char* version;
    enum {
        SVG_BASE_PROFILE_NONE,
        SVG_BASE_PROFILE_FULL,
        SVG_BASE_PROFILE_BASIC,
        SVG_BASE_PROFILE_TINY
    } baseProfile;

} GSvgElementSvgAttributes;


#endif // GVGELEMENTS_H